name: SimpleWaypoints
version: 0.3
api-version: 1.14
author: Stefano Tavonatti; DKolibar
main: tavonatti.stefano.spigot_plugin.waypoints.Main
commands:
  wsave:
    description: save a new waypoint
    usage: /wsave
  wtp:
    description: teleport player to waypoint
    usage: /wtp
  wlist:
    description: list waypoints
    usage: /wlist
  wdelete:
    description: delete a waypoint
    usage: /wdelete
  whome:
    description: teleport to spawn location
    usage: /whome